### ISSUE TITLE
Proposta de melhorias na interface do Juventude

### ISSUE THREAD

**Issue by maxbborges** [IBICT/noosfero#40]
O site juventude.gov.br apresenta diversos pontos onde se tem a necessidade de melhoria na apresentação ou organização das informações que são apresentadas no site. Aqui ficará registrado as propostas de melhorias, que posteriormente serão alinhadas com o Michel para as devidas implementações.

Quando for inserido uma nova proposta, inserir uma nova "task list" citando o comentário, para uma melhor organização. Após a aprovação ou o modificação, marcar o checkbox.

- [ ] https://github.com/IBICT/noosfero/issues/40#issuecomment-350014789
- [ ] https://github.com/IBICT/noosfero/issues/40#issuecomment-350045078
- [x] https://github.com/IBICT/noosfero/issues/32
- [ ] https://github.com/IBICT/noosfero/issues/30
- [ ] https://github.com/IBICT/noosfero/issues/21 gerado do relatorio da https://github.com/IBICT/noosfero/issues/15
- [ ] https://github.com/IBICT/noosfero/issues/22 gerado do relatorio da https://github.com/IBICT/noosfero/issues/15
- [x] https://github.com/IBICT/noosfero/issues/23 gerado do relatorio da https://github.com/IBICT/noosfero/issues/15
- [ ] https://github.com/IBICT/noosfero/issues/24 gerado do relatorio da https://github.com/IBICT/noosfero/issues/15
- [ ] https://github.com/IBICT/noosfero/issues/25 gerado do relatorio da https://github.com/IBICT/noosfero/issues/15
- [ ] https://github.com/IBICT/noosfero/issues/26 gerado do relatorio da https://github.com/IBICT/noosfero/issues/15
- [ ] https://github.com/IBICT/noosfero/issues/29

**Comment by maxbborges** [comment]
Foi apresentado ao Michel a quantidade de comunidades existentes no site, muitas delas estão repetidas ou até mesmo sem nenhuma publicação desde a sua criação. 
![comunidades](https://user-images.githubusercontent.com/18174772/33725020-181d65ca-db58-11e7-906f-5d83ebdac245.PNG)

Foi autorizado a exclusão e desativação de algumas dessas comunidades. Além disso, comunidades que eram apenas para testes também estão sendo exibidas sem a necessidade de login.
![comunidades1](https://user-images.githubusercontent.com/18174772/33725098-5627e232-db58-11e7-9b19-b737461fbedc.PNG)

**Comment by maxbborges** [comment]
Considerando a estrutura do site inicial, é proposto uma reorganização dos blocos no site.
Pagina inicial atualmente: 
![atual](https://user-images.githubusercontent.com/18174772/33730322-c56911c6-db66-11e7-86e9-04dc54aaf41c.PNG)

Pagina Inicial Proposta:
![opcao1](https://user-images.githubusercontent.com/18174772/33730341-d4925568-db66-11e7-8c71-9a90a724b1bd.PNG)

Faltando a aprovação do Michel para devidas modificações.

**Comment by maxbborges** [comment]
Pagina Iniciativas em branco  
#32
